version: 2.1
workFlow:
   testDeploy:
       jobs:
         test

jobs: 
  test:
    docker:
       - image:cing/module:17.2.0
    steps:
       -checkout
       -run:
          name: install dependency
          command: npm install
        -run
           name: run test
           command: npm run test
